version: '3'
services:
  node:
    # Dockerfileの場所
    build:
        context: ./
        dockerfile: ./Dockerfile
    working_dir: /var/project/ToDoApp
    # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - ./:/var/project/ToDoApp
    # コンテナ内部の3000を外部から3000でアクセスする
    ports:
      - "3000:3000"
    command: yarn dev
